<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
﻿<div class="footer">
			<div class="alt">
				<div class="foot">
					<p>关于我们</p>
					<a href="###">企业简介</a>
					<a href="###">企业文化</a>
					<a href="###">组织机构</a>
					<a href="###">发展历程</a>
					<a href="###">企业荣誉</a>
					<a href="###">诚聘英才</a>
					<a href="###">联系我们</a>
 
				</div>
				<div class="foot">
					<p>新闻中心</p>
					<a href="###">公司新闻</a>
					<a href="###">行业新闻</a>
				</div>
				<div class="foot">
					<p>产品及解决方案</p>
					<a href="###">产品系列</a>
					<a href="###">解决方案</a>
				</div>
				<div class="foot">
					<p>研发与创新</p>
					<a href="###">核心技术</a>
					<a href="###">技术创新</a>
				</div>
				<div class="foot">
					<p>经典案例</p>
					<a href="###">智慧城市</a>
					<a href="###">智慧高速</a>
					<a href="###">智慧家居</a>
					<a href="###">智慧网络</a>
				</div>
				<div class="foot">
					<p>服务支持</p>
					<a href="###">技术支持</a>
					<a href="###">服务网络</a>
					<a href="###">资料下载</a>
					<a href="###">公司理念</a>
				</div>
				<div style="float: left;margin-left: 5%;margin-top: 20px">
					<div style="float: left">
						<b style="font-size: 22px;color: #409eff;"><i class="el-icon-phone-outline" ></i>
						800-8820-0820</b>
						<p style="color:#666;margin-top: 5px;text-align: left;">周一至周五 9:00-18:00</p>
						<p style="color:#666;margin-top: 20px;text-align: left;color:#999" @click="jubao()">
							<el-link><i class="el-icon-service" >&nbsp;我要举报</i></el-link>
						</p>
					</div>
					<div style="float: left;margin-left: 10px">
						<img src="img/erweima.jpg"  style="width: 100px"/>
					</div>
					
				</div>
			</div>
			<div >
				<p class="alt" style="color:#999; line-height:0;text-align: center;">
				Copyright © 2004 Adobe Systems Incorporated. All rights reserved.   

				</p>
			</div>
		</div>
  